# Site settings
title: 'Allef Sousa'
description: 'Computer Science Student'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/Presentation/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Josh Gerdes'
  email: 'allefsousa_1@hotmail.com'
  twitter_username: 'https://twitter.com/AllefSsousa'
  facebook_username: 'https://www.facebook.com/allefsousas'
  github_username:  'https://github.com/allefsousa'
  linkedin_username: 'https://br.linkedin.com/in/allef-sousa-b1a18175'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
